jMonkey:
    freemarker:
        templateLoaderPath: classpath:/templates
        freemarkerSettings:
            template_update_delay: 5  #刷新模板的周期，单位为秒
            default_encoding: UTF-8 #模板的编码格式
            locale: UTF-8 #本地化设置
            datetime_format: yyyy-MM-dd HH:mm:ss
            time_format: HH:mm:ss
            number_format: 0.####
            boolean_format: true,false
            whitespace_stripping: true
            tag_syntax: auto_detect
            url_escaping_charset: UTF-8
        freemarkerVariables:
            webURL: ${jMonkey.project.domain}
            cssURL: ${jMonkey.project.domain}/css
            libURL: ${jMonkey.project.domain}/lib
            imagesURL: ${jMonkey.project.domain}/images
            scriptsURL: ${jMonkey.project.domain}/scripts
            min: ${jMonkey.script.min}  #script插件是否min包
            systemName: ${jMonkey.project.title} #系统页面title显示内容

spring:
    application:
        name: ${jMonkey.project.name}
    profiles:
        active: dev
    freemarker:
        suffix: .html
        request-context-attribute: request
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    datasource:
        druid:
            driver-class-name: com.mysql.jdbc.Driver
            username: ${jMonkey.datasource.username}
            password: ${jMonkey.datasource.passward}
            url: jdbc:mysql://${jMonkey.datasource.url}?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
            initial-size: 1
            max-active: 20
            min-idle: 1
            max-wait: 60000
            validation-query: select 1 from dual
            validationQueryTimeout: 5
            test-on-borrow: false
            test-on-return: false
            test-while-idle: true
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            filters: log4j2
            filter:
                stat:
                    enabled: true
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: true
                slf4j:
                    enabled: true
                    connection-log-enabled: true
                    connection-close-after-log-enabled: true
                    connection-commit-after-log-enabled: true
                    connection-connect-after-log-enabled: true
                    connection-connect-before-log-enabled: true
                    connection-log-error-enabled: true
                    data-source-log-enabled: true
                    result-set-log-enabled: true
                    statement-log-enabled: true
                wall:
                    enabled: true
                    config:
                        alter-table-allow: false
                        truncate-allow: false
                        drop-table-allow: false
                        #是否允许非以上基本语句的其他语句，缺省关闭，通过这个选项就能够屏蔽DDL
                        none-base-statement-allow: false
                        #检查UPDATE语句是否无where条件，这是有风险的，但不是SQL注入类型的风险
                        update-where-none-check: true
                        #SELECT ... INTO OUTFILE 是否允许，这个是mysql注入攻击的常见手段，缺省是禁止的
                        select-into-outfile-allow: false
                        #是否允许调用Connection.getMetadata方法，这个方法调用会暴露数据库的表信息
                        metadata-allow: true
                        #允许多条sql一起执行
                        multiStatementAllow: true
                    #对被认为是攻击的SQL进行LOG.error输出
                    log-violation: true
                    #对被认为是攻击的SQL抛出SQLExcepton
                    throw-exception: true
                    db-type: mysql
                web-stat-filter:
                    enabled: true
                    url-pattern: /*
                    exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
                    #你可以配置principalSessionName，使得druid能够知道当前的cookie的用户是谁
                    #principal-cookie-name: admin
                    #你可以配置principalSessionName，使得druid能够知道当前的session的用户是谁
                    #principal-session-name: admin
                    #设置profileEnable能够监控单个url调用的sql列表。
                    profile-enable: true
                    #session统计功能
                    session-stat-enable: false
                    #最大session数
                    session-stat-max-count: 100000
                stat-view-servlet:
                    #allow: ${GATEWAY_HOST:172.26.114.241}
                    enabled: true
                    login-username: admin
                    login-password: 123456
                    url-pattern: /druid/*
                    #允许清除记录
                    reset-enable: false
                aop-patterns: com.wang.jmonkey.modules.*.service.*

# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: ${jMonkey.project.port}
    servlet:
        context-path: /${jMonkey.project.name}

#mybatis
mybatis-plus:
    mapper-locations: classpath:mapper/*.xml
    typeAliasesPackage: com.wang.jmonkey.modules.*.entity #实体扫描，多个package用逗号或者分号分隔
    global-config:
        id-type: 3 #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
        field-strategy: 2 #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
        db-column-underline: true #驼峰下划线转换
        refresh-mapper: true #刷新mapper 调试神器
        #capital-mode: true #数据库大写下划线转换
        #key-generator: com.baomidou.springboot.xxx #序列接口实现类配置
        logic-delete-value: -1 #逻辑删除配置
        logic-not-delete-value: 0
        #meta-object-handler: com.baomidou.springboot.xxx #自定义填充策略接口实现
        sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector #自定义SQL注入器
    configuration:
        map-underscore-to-camel-case: true
        cache-enabled: false
        call-setters-on-nulls: true

#logging
#logging:
#    level: warn